---
- hosts: localhost    
  gather_facts: yes
  connection: local
  vars:
    fg-id: 1
    
  tasks:
    - name: delete
      fortios_ipv4_policy:
        host: 192.168.0.101
        username: admin
        password: 1qaz!QAZ
        id: {{ fg-id }}      
        state: absent
