---
- hosts: localhost
  gather_facts: yes
  connection: local
  
  tasks:
    - name: Backup current config
      connection: local
      fortios_config:
        host: 192.168.0.101
        backup: yes
        backup_path: /etc/ansible/backup/
