---
- hosts: localhost
  gather_facts: yes
  connection: local
  
  tasks:
    - name: Backup current config
      connection: local
      fortios_config:
        host: 192.168.0.101
        username: admin
        password: 1qaz!QAZ
        file_mode: yes
        config_file: /etc/ansible/backup/abc.txt
