---
- hosts: localhost
  gather_facts: yes
  connection: local
  
  tasks:
    - name: Backup current config
      fortios_config:
        host: 192.168.0.101
        username: admin
        password: 1qaz!QAZ
        backup_path: /etc/ansible/backup/  # バックアップ先ディレクトリ
        backup: yes  # バックアップする指定
