---
- hosts: 192.168.0.101
vars:
host: "192.168.0.101"
username: "admin"
password: "1qaz!QAZ"
vdom: "global"
tasks:
- name: Allow external DNS call
  fortios_ipv4_policy:
    host: 192.168.0.101
    username: admin
    password: 1qaz!QAZ
    id: 1
    src_addr: 192.168.0.1/24
    dst_addr: all
    service: dns
    nat: True
    state: present
    policy_action: accept
    logtraffic: disable
