---
- hosts: localhost    # 実機を対象としない。ここではダミー的に localhost とする
  gather_facts: no
  connection: local

  tasks:
    - name: Register google DNS
      fortios_address:
        host: 192.168.0.101
        username: admin
        password: 1qaz!QAZ
        state: present
        name: "google_dns"
        type: ipmask
        value: 8.8.8.8
