---
- hosts: localhost    
  gather_facts: no
  connection: local
  
  vars_prompt:
    - name: "name"
      prompt: "what is the source ip?"
    - name: "quest"
      prompt: "what is the destination ip?"
    - name: "favcolor"
      prompt: "what is allowed service?"
  
  tasks:
    - name: Register google DNS
      fortios_address:
        host: 192.168.0.101
        username: admin
        password: 1qaz!QAZ
        state: present
        name: "google_dns"
        type: ipmask
        value: 8.8.8.8
        
    - name: Allow external DNS call
      fortios_ipv4_policy:
        host: 192.168.0.101
        username: admin
        password: 1qaz!QAZ
        id: 0        
        src_addr: all
        dst_addr: all
        service:
          - HTTP
        nat: True
        state: present
        policy_action: accept
logtraffic: disable
