---
- hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: manage policy
      fortios_ipv4_policy:
        host: "{{ inventory_hostname }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        id: 1
        name: ALL 
        src_addr: all
        dst_addr: all
        services:
          - HTTP
          - HTTPS
        state: present
        policy_action: accept
