- hosts: localhost
  gather_facts: no
  vars:
     username: "admin"
     password: "1qaz!QAZ"
     vdom: "root"
     host: "192.168.0.107"
  tasks:
    - name: Get system resource usage
      fortiosconfig:
       config: "system resource usage"
       action: "monitor"
       host:  "{{ host }}"
       username: "{{ username }}"
       password: "{{ password }}"
       vdom: "{{ vdom }}"
