---
- hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: manage policy
      fortios_ipv4_policy:
        host: "{{ inventory_hostname }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        id: 1
        src_intf: port1
        src_addr: all
        dst_intf: port2
        dst_addr: all
        services:
          - FTP
          - HTTP
          - HTTPS
        state: present
        policy_action: accept
